### ISSUE TITLE
Include Error

### ISSUE THREAD

**Issue by LoubiTek** [ikalnytskyi/termcolor#16]
I'm under Code :: Blocks with the GCC compiler.
In the IDE, I added the file to my project.
I wanted to try to include your file to use it in addition to pdcurses but it does not seem to find the .hpp.
I put this line: #include <termcolor / termcolor.hpp>

Here is the error:
||=== Build: Debug in testapp (compiler: GNU GCC Compiler) ===|
C:\Users\Utilisateur\Desktop\Logiciels Programmations\Mes_Programmes\C++\testapp\main.cpp|2|fatal error: termcolor/termcolor.hpp: No such file or directory|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

I would like to point out that I still have a lot of trouble understanding the general functioning of compilers and compiling, command lines and the addition of libs.
And then I have to learn to use the IDE and its options as well as the C/C ++ language. Especially as I am on Windows 10, not really help in apprenticeship compared to the say of the Linuxiens. ^^

So I do not know if it's a manipulation fault or if it's really the file itself that is not taken into account by the compiler I'm using.
But from what I've read in the documentation, it should work under windows?

If someone passes by and wants to answer me, I would be very happy to learn from where the error came. Thank you!

**Comment by ikalnytskyi** [comment]
@LoubiTek sorry for the delay, being a bit busy.

You need to drop `termcolor.hpp` near your `main.cpp`, and then you can include it like this:

```cpp
#include "termcolor.hpp"
```

Alternatively, you can drop the whole folder `termcolor/termcolor.hpp` and use corresponding path in `#include` directive.

**Comment by LoubiTek** [comment]
I put the file at the root of my file or there is main.cpp.
Without past it the IDE. He create a folder header.
I did the inclusion as you said (#include "termcolor.hpp")
This compiles without error!
Thanks, it works fine now.

So the mistake came from the inclusion that was bad.
I'll fix it and run a pull request for documentation to solve the problem for new people who would use your .hpp file without worries.

**Comment by ikalnytskyi** [comment]
@LoubiTek glad it helps. Basically you need to remember few simple rules:

- `#include "termcolor/termcolor.hpp"` – search for "termcolor/termcolor.hpp" file relative to the current one (the one with `#include` statement)

- `#include <termcolor/termcolor.hpp>` – search for "termcolor/termcolor.hpp" file relative to folders listed in standard include paths (it's usually specified in IDEs project properties).

I close this issue as it's resolved.
