### ISSUE TITLE
Windows 10 Virtual Terminal Sequence Support

### ISSUE THREAD

**Issue by slurps-mad-rips** [ikalnytskyi/termcolor#22]
Hello!

Windows 10 supports [VT100](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) escape sequences with a call to `SetConsoleMode` and the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag. Using this would give Windows users more features. You can also, for non Windows 10 versions, fallback to the current behavior.

**Comment by ikalnytskyi** [comment]
@slurps-mad-rips thanks for reaching out to me. It's definitely in my TODO, and now I know at least someone would like to have this.

The main challenge right now for me is:

* Let `termcolor` to call `SetConsoleMode(ENABLE_VIRTUAL_TERMINAL_PROCESSING)` on Windows 10 and use ANSI escape sequences.

* Let users to do the call instead and check whether `ENABLE_VIRTUAL_TERMINAL_PROCESSING` enabled or not when colored manipulators are used. This I like more in a sense we don't introduce side effect but it would require to introduce additional runtime cost. 

* Use some `#define TERMCOLOR_WINDOWS10_ASCII` to unconditionally use ASCII sequences if defined.

* Come up with another idea that will not require additional runtime cost, or will provide a way to do not pay for runtime checks.

I'll think about it and will come up with some solution for sure. :)
