### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by NeroBurner** [ikalnytskyi/termcolor#24]
Could you create a tag to mark a release?

If you don't need semantic versioning you could use a `vYY.MM.X` versioning scheme. For examle `v18.10.1`

Otherwise I would have to create a fork and tag myself to add your project to Hunter just to have a persistent reference

**Comment by ikalnytskyi** [comment]
`v1.0.0` is here https://github.com/ikalnytskyi/termcolor/releases/tag/v1.0.0
