### ISSUE TITLE
Add support for std::clog

### ISSUE THREAD

**Issue by janekb04** [ikalnytskyi/termcolor#31]
`clog` is just like `cerr`, just buffered. Output to `cerr` can be formatted, but to `clog` - no. I think that support for formatting `clog` should be added.

**Comment by ikalnytskyi** [comment]
@janekb04 I just checked, `clog` message can be formatted too. Are you sure `clog` stream is attached to `tty`?

**Comment by ikalnytskyi** [comment]
@janekb04 Please let me know if you have some issues. `std::clog`  should work. I even added its check to the test 8996888de7276631a90c69e35cd2db4346decf59.
