### ISSUE TITLE
Control Characters on Windows Terminal

### ISSUE THREAD

**Issue by thomthom** [ikalnytskyi/termcolor#49]
I was shopping around for a C++ lib to simplify text color to terminal apps. I found this, but notice it uses special handling for Windows. However, I noticed that control characters works in Windows Terminal (and VSCode terminal)

Would be interesting to have a switch to make Windows builds to also use control characters. Could this be of interest for this lib?

**Comment by ikalnytskyi** [comment]
Having such a switch should be beneficial for https://github.com/ikalnytskyi/termcolor/issues/29. I'll see what I can do.
