### ISSUE TITLE
Use with stringstreams

### ISSUE THREAD

**Issue by stonier** [ikalnytskyi/termcolor#5]
I naively thought the stream manipulators here would work with a `std::stringstream` object, for later relaying to a terminal. 

As it currently stands though, the library does a strict check on the stream to see if it's a terminal stream via [termcolor.hpp#445](https://github.com/ikalnitsky/termcolor/blob/master/include/termcolor/termcolor.hpp#L445), which it promptly fails and aborts.

Nonetheless, by just ensuring that function always returns true, I can get the following code to work quite normally.

```
#include <termcolor/termcolor.hpp>
#include <iostream>
#include <sstream>

int main(int argc, char **argv) {
  std::stringstream sstream;
  sstream << termcolor::cyan << "Dude" << termcolor::reset;
  std::cout << sstream.str() << std::endl;
  return 0;
}
```

This, I imagine is quite a common and practical use case. How important is it for strict terminal checks? Is this something that can be dropped or potentially made optional?

**Comment by ikalnitsky** [comment]
@stonier Hm.. Originally the idea was is to be protected from Unix pipes. For instance, if you run program that way -

```bash
$ ./my_program > out.txt
```

`stdout` is not a tty, and ASCII characters won't get to output file (which is desired behaviour in most case).

However, I think we need to think how to avoid it and fix with `std::stringstream`.

**Comment by ikalnitsky** [comment]
Well I think we can do the following things:

* if stream is either `stdout` or `stderr` and is not `atty` -> strip ASCII escape sequences
* otherwise - use them

In that case the case with redirection of standard io streams and having buffered string stream will be covered. However, I'm not very happy with such non obvious complexity. Need to think a bit more.

**Comment by stonier** [comment]
Aha, I see.

Your logic sounds fine.

Though I do agree, with a stringstream you start moving into the realm of letting the user get himself into trouble (or not) and you cannot provide the protection there as he may eventually pipe that string out as you illustrated above.

Perhaps a better alternative is equipping the user with a tool that they can use to strip output from a termcolor enabled program? e.g.

```
$ ./my_program | strip_termcolor_sequences > out.txt
```

**Comment by ikalnitsky** [comment]
@stonier We can't be sure such a tool will be widely distributed. I start thinking about explicit manipulator, like:

```cpp
std::cout << termcolor::force << termcolor::red << "RED message" << termcolor::reset << std::endl;
```

Or maybe it's better to make **force** mode by default, and use **tty** mode to strip colors if output isn't tied with tty:

```cpp
std::cout << termcolor::tty << termcolor::red << "RED message" << termcolor::reset << std::endl;
```

Anyway, thank you very much for raising an important concern! I'll try to come up with solution.

**Comment by stonier** [comment]
The manipulator approach is interesting.

I would offer one perspective.  For a user of a program that utilises this library, there are many ways of stripping colour codes if you wish (google for ['bash strip terminal color sequences'](https://www.google.co.kr/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=bash%20strip%20terminal%20color%20sequences), but there is *no* way of re-inserting colour codes if the library/programmer has decided to strip them for you.

**Comment by davidvanlaatum** [comment]
should at least fix the crash for now ;) even if its just assume its not a tty

**Comment by ikalnytskyi** [comment]
@davidvanlaatum wow! nobody told be that there's a crash! it definitely needs to be fixed.

**Comment by davidvanlaatum** [comment]
yep fileno(NULL) goes boom at least on osx

**Comment by ikalnytskyi** [comment]
I'll prepare a fix and add test to CI for that case. Thanks a lot! 

>  as for determining if a stream is a tty I suggest some ability to provide a user function to determine if it is

I agree on this. I'll add it very soon.

**Comment by ikalnytskyi** [comment]
Fixed segmentation fault in https://github.com/ikalnytskyi/termcolor/commit/519358f07c81bfa97bce0c7769edeb3703c99cbd.

**Comment by gelldur** [comment]
Any updates on this :) ?

**Comment by ikalnytskyi** [comment]
@gelldur well, I come up with a solution. will implement it pretty soon.

**Comment by gelldur** [comment]
Nice thx! Updating fork :)
