### ISSUE TITLE
Wheel support for linux aarch64/x86

### ISSUE THREAD

**Issue by odidev** [ikalnytskyi/termcolor#50]
**Summary**
Installing termcolor on aarch64/x86 via pip using command "pip3 install termcolor" tries to build wheel from source code

**Problem description**
termcolor doesn't have wheel for aarch64/x86 on PyPI repository. So, while installing termcolor via pip on aarch64/x86 machine, pip builds the source code resulting in it takes more time to install termcolor. Making wheel available for aarch64/x86 will benefit aarch64/x86 users by minimizing termcolor installation time.

**Expected Output**
Pip should be able to download termcolor wheel from PyPI repository rather than building it from source code.

@termcolor-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make termcolor wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by ikalnytskyi** [comment]
Hey @odidev,

You have reported it wrongly. This repository contains a C++ header only library and has nothing to do with [a Python module of the same name](https://pypi.org/project/termcolor). Please reach out to maintainers of Python library instead.
