### ISSUE TITLE
ANSI getting printed instead of colored text

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [ikalnytskyi/termcolor#62]
Hey, I'm Yuvraj.
Thank you for the package it's been awesome but for a long time one problem is bothering me. Instead of printing colored texts for one instance in my project it is just printing ANSI sequence in CMD.

Here's my code. 

- Printing Hanlder
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/0612fd8114e980c2dea3458d828e91ba193ba812/helpers/CustomCI.py#L1-L26

- And this particular file is causing issues
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/blob/0612fd8114e980c2dea3458d828e91ba193ba812/protect.py#L1-L171

![image](https://user-images.githubusercontent.com/52948878/116003500-d56dc200-a61b-11eb-8284-b6451238f03b.png)

Can you help me out?

**Comment by YuvrajRaghuvanshiS** [comment]
Surprisingly enough after running a os.system() line it is working in this instance

![image](https://user-images.githubusercontent.com/52948878/116003587-3ac1b300-a61c-11eb-8dfa-5d6c4f7cd744.png)

**Comment by ikalnytskyi** [comment]
I assumed you confused this library with Python one. Please report this issue to Python project instead.
