### ISSUE TITLE
Please publish new 2.0.1 / 2.1.0 release

### ISSUE THREAD

**Issue by ras0219-msft** [ikalnytskyi/termcolor#69]
Users in vcpkg have requested a newer version than is currently included in a release tag (https://github.com/microsoft/vcpkg/pull/23329).

Could you please consider pushing a new release tag including the latest changes?

**Comment by ikalnytskyi** [comment]
Sorry for taking so long. I just pushed the tag.

https://github.com/ikalnytskyi/termcolor/releases/tag/v2.1.0
