### ISSUE TITLE
Build failure: unknown type name `uint8_t`

### ISSUE THREAD

**Issue by wardw** [ikalnytskyi/termcolor#75]
I noticed a simple "hello world" program fails to build due to missing the header [`<cstdint>`](https://en.cppreference.com/w/cpp/header/cstdint) for the use of `uint8_t`.

Testing with a single file `main.cpp`

    #include <termcolor/termcolor.hpp>
    #include <iostream>

    int main(int argc, char **argv)
    {
        std::cout << termcolor::green << "Hello, world!" << termcolor::reset << std::endl;
    }

and building with

    clang++ main.cpp -o hello -g -I./termcolor/include

the build fails with a bunch of errors of the form `./termcolor/include/termcolor/termcolor.hpp:200:15: error: unknown type name 'uint8_t'`.  Tested on Fedora Linux with clang-18.

Of course, adding `#include <cstdint>` to `termcolor.h` fixes the problem.  

As an aside, I noticed that the README example puts `<iostream>` _before_ `termcolor.h`, which makes me speculate that this might be silently working on some platforms depending on the implementation of `<iostream>`.  That might explain why this wasn't caught already?  But of course that would be to depend on an implementation detail, and more generally would be to make Termcolor dependent on the order of includes, which I imagine is also not by design.

That aside, thanks for a great library!

**Comment by ikalnytskyi** [comment]
Fixed by https://github.com/ikalnytskyi/termcolor/pull/72
